import { PROJECTS, RESEARCH } from './data.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const titleCase=s=>String(s).replace(/\b\w/g,c=>c.toUpperCase());

const tracks=[['AI / Scientific ML',7],['Cybersecurity / PQC',5],['Robotics / Autonomous Systems',6],['Computer Vision / 3D',5],['Aerospace / Space',10],['Quantum Computing / Physics',6],['Photonics / Optics',4],['Biology / Genetics / Chemistry',5],['Quantitative Finance',1],['Systems / Research Infrastructure',1]];

function renderTracks(){const root=$('#trackGrid'); if(!root)return; root.innerHTML=tracks.map(([n,c],i)=>`<article class="track-card"><b>${esc(n)}</b><span>${c} programme items</span><i style="--w:${46+i*5}%"></i></article>`).join('')}

// ===== Projects =====
const projectGrid=$('#projectGrid'),search=$('#projectSearch'),domain=$('#projectDomain'),status=$('#projectStatus'),sort=$('#projectSort');
const projectDomains=[...new Set(PROJECTS.map(p=>p.domain))].sort();
if(domain)domain.innerHTML+=projectDomains.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');
const prettyStatus=s=>s==='in-progress'?'In progress':titleCase(s);
const publicationStateBySlug={
  'quasar-post-quantum-security-platform':{label:'Ongoing publication', tone:'green'},
  'aqualink-earth-observation-intelligence':{label:'Published research', tone:'blue'},
  'inflow-ai-flood-intelligence':{label:'Published research', tone:'blue'}
};
const publicationBadge=p=>publicationStateBySlug[p.slug]?`<span class="publication-badge publication-${publicationStateBySlug[p.slug].tone}">${esc(publicationStateBySlug[p.slug].label)}</span>`:'';

const PUBLICATIONS={
  aqualink:{code:'PUBLICATION P01 · EARTH OBSERVATION',title:'AquaLink Earth Observation Intelligence',subtitle:'Published research track for satellite water intelligence.',status:'PUBLISHED',output:'Published research',record:'DOI placeholder',overview:'AquaLink explores Earth-observation-assisted monitoring for water scarcity, contamination risk and intervention planning using remote sensing, environmental data fusion and AI-supported decision systems.',evidence:[['DOI','Placeholder / to be inserted'],['Manuscript','Published / archived'],['Preprint','Optional placeholder'],['Evidence','LinkedIn credential record / publication archive'],['Research state','Published research direction'],['Impact angle','Water intelligence, environmental risk and humanitarian planning']]},
  inflow:{code:'PUBLICATION P02 · FLOOD INTELLIGENCE',title:'INFLOW-AI Flood Intelligence',subtitle:'Published research track for flood early-warning analytics.',status:'PUBLISHED',output:'Published research',record:'DOI placeholder',overview:'INFLOW-AI targets flood prediction, environmental sensing and early-warning support through hydrological signals, geospatial intelligence and AI forecasting workflows.',evidence:[['DOI','Placeholder / to be inserted'],['Manuscript','Published / archived'],['Preprint','Optional placeholder'],['Evidence','LinkedIn credential record / publication archive'],['Research state','Published research direction'],['Impact angle','Flood response, resilience and environmental decision support']]},
  quasar:{code:'PUBLICATION P03 · POST-QUANTUM SECURITY',title:'QUASAR Post-Quantum Security Research',subtitle:'Ongoing manuscript and publication pipeline.',status:'GREEN / ONGOING',output:'Manuscript in preparation',record:'Preprint placeholder',overview:'QUASAR focuses on post-quantum security engineering, anomaly detection, observability and response automation with a publication path oriented toward rigorous evaluation and deployable security architecture.',evidence:[['Manuscript','In preparation'],['Preprint','Placeholder / draft slot'],['Evidence','LinkedIn credential record / manuscript updates'],['Research state','Ongoing publication'],['Novelty wedge','PQC + cyber observability + AI response automation'],['Target outcome','Submission-ready technical manuscript']]},
  future:{code:'PUBLICATION P04 · FUTURE FRONTIER PAPERS',title:'Future Frontier Papers',subtitle:'Preprint and DOI placeholders for upcoming research outputs.',status:'PREPRINT PLACEHOLDER',output:'Future papers',record:'Placeholder',overview:'Reserved placeholder for future papers across robotics, quantum dynamics, geo-optics, photonics, aerospace systems and other frontier research programmes in the portfolio.',evidence:[['Repository','Placeholder'],['DOI','Placeholder'],['Venue','Target journal / conference'],['Evidence','LinkedIn / future archive'],['Research state','Pipeline / concept staging'],['Target outcome','Preprint, manuscript and archival publication slots']]}
};
function openPublication(id){const pub=PUBLICATIONS[id];if(!pub)return;$('#publicationCode').textContent=pub.code;$('#publicationTitle').textContent=pub.title;$('#publicationSubtitle').textContent=pub.subtitle;$('#publicationStatus').textContent=pub.status;$('#publicationOutput').textContent=pub.output;$('#publicationRecord').textContent=pub.record;$('#publicationOverview').innerHTML=`<h3>Research overview</h3><p>${esc(pub.overview)}</p><h3>Publication intent</h3><p>This dossier records the current publication pathway, evidence placeholders and output structure for the research item.</p>`;$('#publicationEvidence').innerHTML=`<h3>Evidence / record ledger</h3><div class="pub-evidence-grid">${pub.evidence.map(([k,v])=>`<b>${esc(k)}</b><span>${esc(v)}</span>`).join('')}</div>`;$('#publicationDialog').showModal()}

function projectCard(p){return `<article class="project-card" data-id="${p.id}"><div class="project-top"><span class="project-no">PROJECT ${String(p.id).padStart(2,'0')}</span><span class="status-chip ${p.status}">${esc(prettyStatus(p.status))}</span></div><div class="project-body"><span class="project-domain">${esc(p.domain)}</span><h3>${esc(p.title)}</h3>${publicationBadge(p)}<p>${esc(p.summary)}</p><div class="stack-row">${p.stack.slice(0,6).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="project-foot"><span class="project-level">${esc(p.level)}</span><button class="project-open" data-open-project="${p.id}" type="button">Open dossier</button></div></div></article>`}
function filteredProjects(){const q=(search?.value||'').trim().toLowerCase();let arr=PROJECTS.filter(p=>{const blob=[p.title,p.domain,p.summary,p.level,p.objective,...p.stack,...(p.capabilities||[])].join(' ').toLowerCase();return(!q||blob.includes(q))&&(!domain||domain.value==='all'||p.domain===domain.value)&&(!status||status.value==='all'||p.status===status.value)});if(sort?.value==='title')arr=[...arr].sort((a,b)=>a.title.localeCompare(b.title));else if(sort?.value==='status')arr=[...arr].sort((a,b)=>a.status.localeCompare(b.status)||a.id-b.id);else arr=[...arr].sort((a,b)=>a.id-b.id);return arr}
function renderProjects(){if(!projectGrid)return;const arr=filteredProjects();projectGrid.innerHTML=arr.map(projectCard).join('')||`<div class="track-card"><b>No matching projects</b><span>Adjust the filters.</span></div>`;$('#projectCountLabel').textContent=`${arr.length} / ${PROJECTS.length} projects`;$('#projectFilterLabel').textContent=domain?.value==='all'?'All domains':domain?.value||'All domains';$('#programmeBar').style.width=`${Math.max(4,(arr.length/50)*100)}%`}
[search,domain,status,sort].filter(Boolean).forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',renderProjects));

const bulletList=items=>`<ul class="dossier-list">${(items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const architectureFlow=items=>`<div class="architecture-flow">${(items||[]).map((x,i)=>`${i?'<span class="arch-arrow">→</span>':''}<span class="arch-node">${esc(x)}</span>`).join('')}</div>`;
let currentProject=null;
function resetProjectTabs(){$$('[data-pd-tab]').forEach((b,i)=>{b.classList.toggle('active',i===0);b.setAttribute('aria-selected',String(i===0))});$$('[data-pd-panel]').forEach((panel,i)=>panel.hidden=i!==0)}
function openProject(id){const p=PROJECTS.find(x=>x.id===Number(id));if(!p)return;currentProject=p;$('#projectDossierCode').textContent=`PROJECT ${String(p.id).padStart(2,'0')} · ${p.domain}`;$('#projectDossierTitle').textContent=p.title;$('#projectDossierSubtitle').textContent=p.summary;$('#projectDossierStatus').textContent=prettyStatus(p.status).toUpperCase();$('#projectDossierDomain').textContent=p.domain;$('#projectDossierMaturity').textContent=p.level;$('#projectDossierProgramme').textContent=p.year||'2026+';
  $('#projectOverview').innerHTML=`<div class="dossier-copy">${publicationStateBySlug[p.slug]?`<div class="publication-hero ${publicationStateBySlug[p.slug].tone}"><span>Research / publication tracker</span><b>${esc(publicationStateBySlug[p.slug].label)}</b></div>`:''}<h3>Mission objective</h3><p>${esc(p.objective)}</p><h3>Current engineering state</h3><p>${esc(p.currentWork)}</p><h3>System summary</h3><p>${esc(p.summary)}</p><div class="dossier-tags">${p.stack.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>`;
  $('#projectArchitecture').innerHTML=`<div class="dossier-copy"><h3>System architecture</h3><p>The architecture is structured as explicit modules so interfaces, failure modes and performance can be tested independently.</p>${architectureFlow(p.architecture)}<h3>Primary interfaces</h3>${bulletList(p.interfaces)}</div>`;
  $('#projectCapabilities').innerHTML=`<div class="dossier-copy"><h3>Core capabilities</h3>${bulletList(p.capabilities)}<h3>Why it belongs in the portfolio</h3><p>This project demonstrates ${esc(p.domain.toLowerCase())} engineering through a system that is intended to be runnable, inspectable and measurable rather than a static concept.</p></div>`;
  $('#projectValidation').innerHTML=`<div class="dossier-copy"><h3>Validation strategy</h3>${bulletList(p.validation)}<h3>Engineering gate</h3><p>A subsystem moves from implementation work into the built state only when its behaviour can be reproduced and checked against an appropriate baseline or invariant.</p></div>`;
  $('#projectEngineering').innerHTML=`<div class="dossier-copy"><h3>Engineering notes</h3>${bulletList(p.engineeringNotes)}<h3>Technical stack</h3><div class="dossier-tags">${p.stack.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>`;
  $('#projectRoadmap').innerHTML=`<div class="dossier-copy"><h3>Current roadmap</h3>${bulletList(p.roadmap)}<h3>Next milestone</h3><p>${p.status==='built'?'Hardening, benchmarking and documentation are the current focus.':'The next milestone is a reproducible core implementation with tests and measurable outputs.'}</p></div>`;
  $('#projectRisks').innerHTML=`<div class="dossier-copy"><h3>Known technical risks</h3>${bulletList(p.risks)}<h3>Mitigation approach</h3><p>Risks are handled through modular design, explicit assumptions, benchmark-driven development, failure injection where appropriate and conservative claims about unfinished work.</p></div>`;
  $('#projectCompareBtn').textContent=compareIds.includes(p.id)?'Remove from comparison':'Add to comparison';resetProjectTabs();renderTechnicalDive(p);$('#projectDialog').showModal()}
projectGrid?.addEventListener('click',e=>{const b=e.target.closest('[data-open-project]');if(b)openProject(b.dataset.openProject)});
$$('[data-pd-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-pd-tab]').forEach(b=>b.classList.toggle('active',b===btn));$$('[data-pd-panel]').forEach(panel=>panel.hidden=panel.dataset.pdPanel!==btn.dataset.pdTab)}));
$('#projectTechnicalModeBtn')?.addEventListener('click',()=>setMode(document.body.classList.contains('technical-mode')?'recruiter':'technical'));

// ===== Research =====
const researchGrid=$('#researchGrid'),researchSearch=$('#researchSearch'),researchDomain=$('#researchDomain');
const researchDomains=[...new Set(RESEARCH.map(r=>r.domain))].sort();if(researchDomain)researchDomain.innerHTML+=researchDomains.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');
function researchCard(r){const statusLabel=(r.statusLabel||'In progress').toUpperCase();return `<article class="research-card"><div class="research-index">R${String(r.id).padStart(2,'0')}</div><div><span class="research-domain">${esc(r.domain)}</span><div class="research-status">${esc(statusLabel)}</div><h3>${esc(r.title)}</h3><p>${esc(r.question)}</p><div class="novelty-box"><b>Novelty wedge</b><p>${esc(r.novelty)}</p></div><div class="research-actions"><button data-open-research="${r.id}" type="button">Open research dossier</button></div></div></article>`}
function renderResearch(){if(!researchGrid)return;const q=(researchSearch?.value||'').trim().toLowerCase();const arr=RESEARCH.filter(r=>(!researchDomain||researchDomain.value==='all'||r.domain===researchDomain.value)&&(!q||[r.title,r.domain,r.question,r.method,r.novelty,...(r.experiments||[])].join(' ').toLowerCase().includes(q)));researchGrid.innerHTML=arr.map(researchCard).join('')}
function resetResearchTabs(){$$('[data-rd-tab]').forEach((b,i)=>b.classList.toggle('active',i===0));$$('[data-rd-panel]').forEach((panel,i)=>panel.hidden=i!==0)}
function openResearch(id){const r=RESEARCH.find(x=>x.id===Number(id));if(!r)return;$('#researchDossierCode').textContent=`RESEARCH R${String(r.id).padStart(2,'0')} · ${r.domain}`;$('#researchDossierTitle').textContent=r.title;$('#researchDossierSubtitle').textContent=r.statusNote||r.question;$('#researchDossierStatus').textContent=(r.statusLabel||'IN PROGRESS').toUpperCase();$('#researchDossierDomain').textContent=r.domain;$('#researchDossierOutput').textContent=r.target;$('#researchQuestion').innerHTML=`<div class="dossier-copy"><h3>Research question</h3><p>${esc(r.question)}</p><h3>Why this matters</h3><p>${esc(r.novelty)}</p></div>`;$('#researchMethod').innerHTML=`<div class="dossier-copy"><h3>Proposed method</h3><p>${esc(r.method)}</p><h3>Research discipline</h3><p>Method selection is subordinate to the research question: baselines, uncertainty, ablations and negative results remain part of the programme.</p></div>`;$('#researchNovelty').innerHTML=`<div class="dossier-copy"><h3>Novelty hypothesis</h3><p>${esc(r.novelty)}</p><h3>Novelty gate</h3><p>${esc(r.noveltyGate)}</p></div>`;$('#researchExperiments').innerHTML=`<div class="dossier-copy"><h3>Experiment programme</h3>${bulletList(r.experiments)}</div>`;$('#researchBaselines').innerHTML=`<div class="dossier-copy"><h3>Baseline requirements</h3>${bulletList(r.baselines)}<p>No paper is presented as groundbreaking merely because the topic is frontier; the contribution must survive comparison with strong baselines.</p></div>`;$('#researchDeliverables').innerHTML=`<div class="dossier-copy"><h3>Reproducible paper package</h3>${bulletList(r.deliverables)}<h3>Target output</h3><p>${esc(r.target)}</p></div>`;resetResearchTabs();$('#researchDialog').showModal()}
researchSearch?.addEventListener('input',renderResearch);researchDomain?.addEventListener('change',renderResearch);researchGrid?.addEventListener('click',e=>{const b=e.target.closest('[data-open-research]');if(b)openResearch(b.dataset.openResearch)});document.querySelector('#publications')?.addEventListener('click',e=>{const b=e.target.closest('[data-open-publication]');if(b)openPublication(b.dataset.openPublication)});document.querySelector('[data-close-publication]')?.addEventListener('click',()=>$('#publicationDialog').close());
$$('[data-rd-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-rd-tab]').forEach(b=>b.classList.toggle('active',b===btn));$$('[data-rd-panel]').forEach(panel=>panel.hidden=panel.dataset.rdPanel!==btn.dataset.rdTab)}));
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));

// ===== Theme / modes / clocks / scroll =====
$('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('portfolio-theme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('portfolio-theme')==='light')document.body.classList.add('light');
function clocks(){const n=new Date();const london=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(n);const nairobi=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Nairobi',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(n);const date=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(n);$('#liveClock').textContent=london;$('#bristolClock').textContent=london;$('#nairobiClock').textContent=nairobi;$('#ribbonLocal').textContent='BRS '+london;$('#ribbonNbo').textContent='NBO '+nairobi;$('#ribbonDate').textContent=date}clocks();setInterval(clocks,1000);
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=(h?scrollY/h*100:0)+'%'});
const rotator=['AUTONOMOUS SCIENTIFIC SYSTEMS','QUANTUM / PHOTONICS RESEARCH','AEROSPACE & AUTONOMY','CYBERSECURITY & PQC','COMPUTATIONAL BIOLOGY','SOFTWARE SYSTEMS'];let rotI=0;setInterval(()=>{const el=$('#missionRotator');if(!el)return;rotI=(rotI+1)%rotator.length;el.textContent=rotator[rotI]},2800);
function setMode(mode){document.body.classList.toggle('technical-mode',mode==='technical');$$('.mode-chip').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#modeLabel').textContent=mode==='technical'?'Technical / Research':'Research Engineering';localStorage.setItem('portfolio-mode',mode);if(currentProject)renderTechnicalDive(currentProject)}$$('.mode-chip').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('#modeBtn')?.addEventListener('click',()=>setMode(document.body.classList.contains('technical-mode')?'recruiter':'technical'));setMode(localStorage.getItem('portfolio-mode')||'recruiter');

// ===== Route-only mission map =====
const routePoints=[{code:'NBO',name:'Nairobi',p:0,x:82,y:77,event:'Departure / Jomo Kenyatta'},{code:'ADD',name:'Addis Ababa',p:12,x:78,y:65,event:'East Africa climb corridor'},{code:'KRT',name:'Khartoum',p:26,x:72,y:55,event:'Nile crossing'},{code:'CAI',name:'Cairo',p:41,x:65,y:46,event:'North Africa transition'},{code:'ATH',name:'Athens',p:58,x:56,y:34,event:'Mediterranean checkpoint'},{code:'FCO',name:'Rome',p:72,x:47,y:25,event:'Southern Europe'},{code:'CDG',name:'Paris',p:84,x:34,y:16,event:'Western Europe arrival corridor'},{code:'LON',name:'London',p:93,x:23,y:11,event:'UK transition'},{code:'BRS',name:'Bristol',p:100,x:12,y:10,event:'Arrival / Bristol'}];
let routeProgress=0,routeRunning=true,lastRoute=performance.now();const routeDuration=90000;

const routeAirportMeta={
  NBO:{country:'Kenya',label:'Origin / academic start',hover:'Computing foundations and early academic trajectory.'},
  ADD:{country:'Ethiopia',label:'Software development',hover:'iLabAfrica-style software engineering milestone.'},
  KRT:{country:'Sudan',label:'Scientific data',hover:'Scientific observation and ISS LiDAR contribution stage.'},
  CAI:{country:'Egypt',label:'Cyber research',hover:'QUASAR and cyber defence publication work.'},
  ATH:{country:'Greece',label:'AI research',hover:'AquaLink and INFLOW-AI publication direction.'},
  FCO:{country:'Italy',label:'Aviation systems',hover:'Aircraft systems, maintenance and avionics focus.'},
  CDG:{country:'France',label:'Quant systems',hover:'QuantForge and advanced computational finance tooling.'},
  LON:{country:'United Kingdom',label:'Academic transition',hover:'UWE Bristol higher-education phase.'},
  BRS:{country:'United Kingdom',label:'Current base',hover:'Bristol mission-control base and ongoing programme.'}
};
function enhanceRouteMap(){const wrap=document.querySelector('.route-map-bg');if(!wrap)return; if(!wrap.querySelector('.leg-label')){for(let i=1;i<routePoints.length;i++){const prev=routePoints[i-1],next=routePoints[i];const label=document.createElement('div');label.className='leg-label';label.dataset.legIndex=String(i-1);label.textContent=`${prev.code} → ${next.code}`;label.style.left=((prev.x+next.x)/2)+'%';label.style.top=((prev.y+next.y)/2)+'%';wrap.appendChild(label);}}
  document.querySelectorAll('.checkpoint').forEach(el=>{if(el.querySelector('.airport-hover'))return;const code=el.querySelector('b')?.textContent?.trim();const meta=routeAirportMeta[code]||{};const panel=document.createElement('div');panel.className='airport-hover';panel.innerHTML=`<b>${esc(code||'FIX')} · ${esc(meta.country||'')}</b><small>${esc(meta.label||'AIRPORT NODE')}</small><span>${esc(meta.hover||'Live route checkpoint')}</span>`;el.appendChild(panel);el.tabIndex=0;});
}
function routeState(pct){let next=routePoints[routePoints.length-1],prev=routePoints[0];for(let i=1;i<routePoints.length;i++){if(pct<=routePoints[i].p){next=routePoints[i];prev=routePoints[i-1];break}}const t=Math.max(0,Math.min(1,(pct-prev.p)/Math.max(1,next.p-prev.p)));return{prev,next,t,x:prev.x+(next.x-prev.x)*t,y:prev.y+(next.y-prev.y)*t}}
let lastTrail=0;function spawnRouteTrail(x,y){const wrap=document.querySelector('.route-map-bg');if(!wrap)return;const now=performance.now();if(now-lastTrail<280)return;lastTrail=now;const dot=document.createElement('span');dot.className='route-trail';dot.style.left=x+'%';dot.style.top=y+'%';wrap.appendChild(dot);setTimeout(()=>dot.remove(),1800)}
function updateRoute(){const s=routeState(routeProgress),plane=$('#routePlane');if(plane){plane.style.left=s.x+'%';plane.style.top=s.y+'%';const ang=Math.atan2(s.next.y-s.prev.y,s.next.x-s.prev.x)*180/Math.PI+45;plane.style.transform=`translate(-50%,-50%) rotate(${ang}deg)`}$('#routePercent').textContent=Math.round(routeProgress)+'%';$('#routeNextFix').textContent=s.next.code;const remain=Math.max(0,s.next.p-routeProgress),sec=Math.round(remain/100*(routeDuration/1000));$('#routeEta').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('#routeDistance').textContent=Math.round(6945*routeProgress/100).toLocaleString()+' KM';$('#routeCurrentLeg').textContent=`${s.prev.name} → ${s.next.name}`;const passed=$('#routePassedPath');if(passed)passed.setAttribute('stroke-dasharray',`${routeProgress} ${100-routeProgress}`);$$('.checkpoint').forEach(el=>{const p=+el.dataset.routeP;el.classList.toggle('passed',routeProgress>=p);el.classList.toggle('ghosted',routeProgress>=p+9);el.classList.toggle('active',Math.abs(routeProgress-p)<5)});const legIndex=Math.max(0,routePoints.findIndex(x=>x.code===s.next.code)-1);$$('.leg-label').forEach((el,i)=>el.classList.toggle('active',i===legIndex));spawnRouteTrail(s.x,s.y);const recent=routePoints.filter(x=>routeProgress>=x.p).slice(-4).reverse();$('#routeEvents').innerHTML=recent.map(x=>`<div class="route-event"><b>${x.code}</b>${x.event}</div>`).join('')}
function routeLoop(t){const dt=t-lastRoute;lastRoute=t;if(routeRunning){routeProgress+=dt/routeDuration*100;if(routeProgress>=100){routeProgress=100;routeRunning=false;$('#routePlay').textContent='ROUTE COMPLETE'}updateRoute()}requestAnimationFrame(routeLoop)}enhanceRouteMap();requestAnimationFrame(routeLoop);updateRoute();$('#routePlay')?.addEventListener('click',()=>{if(routeProgress>=100)return;routeRunning=!routeRunning;$('#routePlay').textContent=routeRunning?'PAUSE ROUTE':'RESUME ROUTE'});$('#routeReplay')?.addEventListener('click',()=>{routeProgress=0;routeRunning=true;$('#routePlay').textContent='PAUSE ROUTE';updateRoute()});

// ===== Technology constellation =====
const techData={python:{title:'Python',copy:'Core language across backend systems, machine learning, research prototypes and security automation.',projects:['MediLink','QuantForge','AegisAI','AquaLink','INFLOW-AI']},flask:{title:'FastAPI / Flask',copy:'API and backend frameworks supporting deployable services, dashboards and data-backed systems.',projects:['MediLink','QuantForge','BCE']},java:{title:'Java',copy:'Object-oriented application engineering and desktop systems.',projects:['Pharmacy Desktop System']},cpp:{title:'C / C++',copy:'Systems/game programming and lower-level computational work.',projects:['Uphill Racer','Simulation work']},ml:{title:'PyTorch / TensorFlow',copy:'Deep learning stack for AI, scientific ML, healthcare and autonomous systems.',projects:['MediLink','EEG Wheelchair','SciFormer']},cv:{title:'Computer Vision',copy:'Vision, 3D reconstruction, event cameras, SLAM and Earth observation.',projects:['VisionNav','EventVision','OrbitalVision']},cyber:{title:'Cybersecurity',copy:'Detection, response, forensics and security research.',projects:['AegisAI','QUASAR','DeepTrace']},qiskit:{title:'Quantum / Qiskit',copy:'Quantum dynamics, error correction, compilation, networking and QML research.',projects:['Quantum Dynamics','QEC Lab','Quantum Network']},pqc:{title:'Post-Quantum Cryptography',copy:'ML-KEM / ML-DSA concepts, hybrid security and PQ networking.',projects:['QUASAR','Post-Quantum Network Lab']},iot:{title:'IoT / Sensors',copy:'Physical sensing and telemetry connecting environments to software and analytics.',projects:['AquaLink','EDMAS','Robotics']},ansys:{title:'ANSYS / CFD',copy:'Aerodynamic modelling, engineering simulation and aerospace design studies.',projects:['AeroStruct','CFD Workbench','Formula Student']},avionics:{title:'Avionics',copy:'Systems discipline connecting sensing, failure analysis, navigation and aerospace software.',projects:['AeroGuard','Flight Dynamics','Aviation training']},sql:{title:'SQL / Data',copy:'Relational storage and data pipelines across backend and analytics platforms.',projects:['BCE','MediLink','QuantForge']},cloud:{title:'Cloud / Deploy',copy:'Deployment, observability and service architecture across portfolio applications.',projects:['Render deployments','APIs','Research platforms']}};
const techNodes=$$('.tech-node'),techSvg=$('#techLines');function drawTechLines(){if(!techSvg)return;const shell=$('.tech-map-shell'),r=shell.getBoundingClientRect(),center=$('.tech-core').getBoundingClientRect();techSvg.innerHTML='';techNodes.filter(n=>!n.classList.contains('filtered')).forEach(n=>{const nr=n.getBoundingClientRect();const x1=center.left+center.width/2-r.left,y1=center.top+center.height/2-r.top,x2=nr.left+nr.width/2-r.left,y2=nr.top+nr.height/2-r.top;techSvg.innerHTML+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="rgba(106,169,255,.17)" stroke-width="1.2"/>`})}function selectTech(id){techNodes.forEach(n=>n.classList.toggle('active',n.dataset.techId===id));const d=techData[id];if(!d)return;$('#techTitle').textContent=d.title;$('#techCopy').textContent=d.copy;$('#techCode').textContent='SYSTEM / '+id.toUpperCase();$('#techProjects').innerHTML=d.projects.map(x=>`<span>${esc(x)}</span>`).join('')}techNodes.forEach(n=>n.addEventListener('click',()=>selectTech(n.dataset.techId)));$$('.tech-filter').forEach(b=>b.addEventListener('click',()=>{$$('.tech-filter').forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.techFilter;techNodes.forEach(n=>n.classList.toggle('filtered',f!=='all'&&!n.dataset.group.split(' ').includes(f)));requestAnimationFrame(drawTechLines)}));addEventListener('resize',drawTechLines);requestAnimationFrame(()=>{drawTechLines();selectTech('python')});

// ===== Operations drawer / project comparison =====
const compareIds=[];
function syncCompare(){const tray=$('#compareTray'),chips=$('#compareChips'),open=$('#compareOpen');if(!tray)return;tray.hidden=compareIds.length===0;$('#compareCount').textContent=`${compareIds.length} / 3 selected`;chips.innerHTML=compareIds.map(id=>{const p=PROJECTS.find(x=>x.id===id);return `<span class="compare-chip">${esc(p?.title||'Project')}</span>`}).join('');open.disabled=compareIds.length<2;if(currentProject)$('#projectCompareBtn').textContent=compareIds.includes(currentProject.id)?'Remove from comparison':'Add to comparison'}
function toggleCompare(id){const n=Number(id),i=compareIds.indexOf(n);if(i>=0)compareIds.splice(i,1);else if(compareIds.length<3)compareIds.push(n);syncCompare()}
$('#projectCompareBtn')?.addEventListener('click',()=>{if(currentProject)toggleCompare(currentProject.id)});$('#compareClear')?.addEventListener('click',()=>{compareIds.splice(0);syncCompare()});
$('#compareOpen')?.addEventListener('click',()=>{const selected=compareIds.map(id=>PROJECTS.find(p=>p.id===id)).filter(Boolean);const rows=[['Status',p=>prettyStatus(p.status)],['Domain',p=>p.domain],['Maturity',p=>p.level],['Objective',p=>p.objective],['Architecture',p=>(p.architecture||[]).join(' → ')],['Capabilities',p=>(p.capabilities||[]).join(' · ')],['Validation',p=>(p.validation||[]).join(' · ')],['Roadmap',p=>(p.roadmap||[]).slice(0,3).join(' · ')]];$('#compareTableWrap').innerHTML=`<table class="compare-table"><thead><tr><th>Dimension</th>${selected.map(p=>`<th>${esc(p.title)}</th>`).join('')}</tr></thead><tbody>${rows.map(([label,get])=>`<tr><td>${label}</td>${selected.map(p=>`<td>${esc(get(p))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;$('#compareDialog').showModal()});$('#compareClose')?.addEventListener('click',()=>$('#compareDialog').close());

const opsDrawer=$('#opsDrawer'),opsBackdrop=$('#opsBackdrop');function openOps(){opsDrawer.classList.add('open');opsBackdrop.classList.add('open');opsDrawer.setAttribute('aria-hidden','false')}function closeOps(){opsDrawer.classList.remove('open');opsBackdrop.classList.remove('open');opsDrawer.setAttribute('aria-hidden','true')}$('#opsLaunch')?.addEventListener('click',openOps);$('#opsClose')?.addEventListener('click',closeOps);opsBackdrop?.addEventListener('click',closeOps);$$('[data-ops-target]').forEach(b=>b.addEventListener('click',()=>{closeOps();$(b.dataset.opsTarget)?.scrollIntoView({behavior:'smooth'})}));$('#opsBuilt').textContent=PROJECTS.filter(p=>p.status==='built').length;$('#opsProgress').textContent=PROJECTS.filter(p=>p.status==='in-progress').length;

// ===== Terminal =====
const terminal=$('#terminal'),tout=$('#termOut'),tin=$('#termInput');function openTerminal(){terminal.classList.add('open');terminal.setAttribute('aria-hidden','false');setTimeout(()=>tin.focus(),20)}function closeTerminal(){terminal.classList.remove('open');terminal.setAttribute('aria-hidden','true')}$('#floatTerminal')?.addEventListener('click',openTerminal);$('#terminalHero')?.addEventListener('click',openTerminal);$('#termClose')?.addEventListener('click',closeTerminal);const termCommands={help:'Commands: whoami, projects, research, education, experience, aviation, route, skills, contact, clear, theme',whoami:'Edgar Charles Omondi — software engineering, AI, cybersecurity, avionics, aerospace and research systems.',projects:`${PROJECTS.length} advanced build projects. Built: ${PROJECTS.filter(p=>p.status==='built').length}, in progress: ${PROJECTS.filter(p=>p.status==='in-progress').length}.`,research:'15 frontier research programmes, all tracked as in progress with explicit novelty gates and reproducible experiment plans.',education:'UWE Bristol — BSc (Hons) Computer Science. Earlier university computing at Strathmore University. Aeronautical Engineering (Avionics) technical background.',experience:'Formula Student / engineering simulation context, iLabAfrica software development, ISS LiDAR contribution and multidisciplinary software/AI work.',aviation:'B737-700/800/900, ERJ 170/190, EASA Part-66/145, avionics, multi-engine and optical systems maintenance training represented in the portfolio.',route:'NBO → ADD → KRT → CAI → ATH → FCO → CDG → LON → BRS. Moving route visualisation with checkpoints; no flight simulator.',skills:'Python · FastAPI · Flask · Django · React · Java · C/C++ · PyTorch · TensorFlow · Cybersecurity · Qiskit · IoT · ANSYS',contact:'Email: charlesedgar2005@gmail.com | Base: Bristol, United Kingdom'};tin?.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const c=tin.value.trim().toLowerCase();tin.value='';tout.textContent+=`\nec@portfolio:~$ ${c}\n`;if(c==='clear')tout.textContent='';else if(c==='theme'){$('#themeBtn').click();tout.textContent+='Theme toggled.\n'}else tout.textContent+=(termCommands[c]||"Unknown command. Type 'help'.")+'\n';tout.scrollTop=tout.scrollHeight});


// ===== Shortcut map / global keys =====
const shortcutDialog=$('#shortcutDialog');$('#shortcutFab')?.addEventListener('click',()=>shortcutDialog.showModal());$('#shortcutClose')?.addEventListener('click',()=>shortcutDialog.close());
addEventListener('keydown',e=>{
  if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;
  if(e.key==='?'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();if(!shortcutDialog.open)shortcutDialog.showModal()}
  else if(e.key.toLowerCase()==='t'&&!e.ctrlKey&&!e.metaKey)openTerminal();
  else if(e.key.toLowerCase()==='o'&&!e.ctrlKey&&!e.metaKey)openOps();
  else if(e.key.toLowerCase()==='p'&&!e.ctrlKey&&!e.metaKey)$('#projects')?.scrollIntoView({behavior:'smooth'});
  else if(e.key.toLowerCase()==='r'&&!e.ctrlKey&&!e.metaKey)$('#research')?.scrollIntoView({behavior:'smooth'});
  else if(e.key.toLowerCase()==='m'&&!e.ctrlKey&&!e.metaKey)$('#route-lab')?.scrollIntoView({behavior:'smooth'});
});

// ===== Contact =====
$('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();const n=$('#contactName').value.trim(),o=$('#contactOrg').value.trim(),m=$('#contactMessage').value.trim();const subject=encodeURIComponent(`Portfolio enquiry${o?' · '+o:''}`),body=encodeURIComponent(`Name: ${n}\nOrganisation: ${o}\n\n${m}`);location.href=`mailto:charlesedgar2005@gmail.com?subject=${subject}&body=${body}`});

// ===== Command palette =====
const commandDialog=$('#commandDialog'),commandInput=$('#commandInput'),commandResults=$('#commandResults');const commands=[...PROJECTS.map(p=>({label:p.title,type:'Project',action:()=>openProject(p.id)})),...RESEARCH.map(r=>({label:r.title,type:'Research',action:()=>openResearch(r.id)})),...['projects','research','techmap','route-lab','experience','education','aviation','credentials','contact'].map(id=>({label:'Open '+id.replace('-',' '),type:'Section',action:()=>$('#'+id)?.scrollIntoView({behavior:'smooth'})})),{label:'Open terminal',type:'Tool',action:openTerminal}];function renderCommands(){const q=commandInput.value.trim().toLowerCase(),list=commands.filter(c=>!q||c.label.toLowerCase().includes(q)).slice(0,14);commandResults.innerHTML=list.map((c,i)=>`<div class="command-result" data-command-index="${i}"><b>${esc(c.label)}</b><span>${esc(c.type)}</span></div>`).join('');commandResults._list=list}function openCommand(){commandDialog.showModal();commandInput.value='';renderCommands();setTimeout(()=>commandInput.focus(),20)}$('#commandBtn')?.addEventListener('click',openCommand);$('[data-close-command]')?.addEventListener('click',()=>commandDialog.close());commandInput?.addEventListener('input',renderCommands);commandResults?.addEventListener('click',e=>{const item=e.target.closest('[data-command-index]');if(!item)return;const c=commandResults._list[Number(item.dataset.commandIndex)];commandDialog.close();c?.action()});addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){if(commandDialog?.open)commandDialog.close();if(terminal?.classList.contains('open'))closeTerminal();if(opsDrawer?.classList.contains('open'))closeOps();if($('#compareDialog')?.open)$('#compareDialog').close();if($('#publicationDialog')?.open)$('#publicationDialog').close();if(shortcutDialog?.open)shortcutDialog.close()}});

renderTracks();renderProjects();renderResearch();

// V17: technical dossier and linked system inspection
function renderTechnicalDive(p){const deep=document.querySelector('#technicalDeepDive');if(!deep||!p)return;const technical=document.body.classList.contains('technical-mode');deep.hidden=!technical;const banner=document.querySelector('#techModeNotice');if(banner)banner.textContent=technical?'TECHNICAL MODE · MODULES / VALIDATION / ENGINEERING NOTES':'RECRUITER MODE · SUMMARY VIEW';const modeButton=document.querySelector('#projectTechnicalModeBtn');if(modeButton)modeButton.textContent=technical?'Switch to recruiter view':'Enable technical mode';if(!technical)return;const items=a=>(a||[]).map((s,i)=>`${String(i+1).padStart(2,'0')}. ${s}`).join('\n');deep.innerHTML=`<h3>Engineering Deep Dive · ${esc(p.title)}</h3><p><strong>Objective:</strong> ${esc(p.objective)}</p><h3>Subsystem / data-flow breakdown</h3><pre>${esc(items(p.architecture))}</pre><h3>Interfaces and integration boundaries</h3><pre>${esc(items(p.interfaces))}</pre><h3>Testable assertions and verification</h3><pre>${esc(items(p.validation))}</pre><h3>Engineering design considerations</h3><pre>${esc(items(p.engineeringNotes))}</pre><h3>Risk register</h3><pre>${esc(items(p.risks))}</pre><p><strong>Status:</strong> ${esc(prettyStatus(p.status))} · <strong>Stack:</strong> ${esc(p.stack.join(' / '))}</p>`}
const achievementData=[{title:'Computing foundations',detail:'Strathmore University · BSc Informatics and Computer Science, earlier university study in Kenya.',org:'Strathmore University',badge:'ACADEMIC START'}, {title:'Software engineering practice',detail:'iLabAfrica intern · Python, Django, Flask, JavaScript, REST APIs and relational databases.',org:'iLabAfrica',badge:'SOFTWARE BUILD'}, {title:'Scientific observation and data',detail:'ISS LiDAR EVI-2 contribution · depth data cleaning, noise reduction and feature extraction.',org:'NASA Space Hub',badge:'SPACE DATA'}, {title:'Cyber defence and quantum security',detail:'QUASAR research pipeline · ongoing publication work in post-quantum security, anomaly detection, defence automation and cyber observability.',org:'QUASAR / AegisAI',badge:'ONGOING PUBLICATION'}, {title:'Applied AI systems',detail:'AquaLink and INFLOW-AI now represented as published research directions alongside applied AI engineering work.',org:'AquaLink / INFLOW-AI',badge:'PUBLISHED RESEARCH'}, {title:'Aerospace and avionics',detail:'Boeing 737 NG and Embraer 170 / 190 systems training; aircraft maintenance, avionics and optical/Boeing training.',org:'Boeing / Embraer',badge:'AVIATION SYSTEMS'}, {title:'Quantitative and research computing',detail:'QuantForge research terminal · statistical forecasting, risk analytics, portfolio optimisation and derivatives.',org:'QuantForge',badge:'QUANT SYSTEMS'}, {title:'Bristol higher education',detail:'UWE Bristol · computer science study; Formula Student and ANSYS modelling context.',org:'UWE Bristol',badge:'UK ACADEMIC TRANSITION'}, {title:'Continuing engineering programme',detail:'Portfolio programme of 53 build systems and 15 separate frontier research directions.',org:'Bristol, UK',badge:'MISSION CONTINUES'}];
function showAchievement(i){const e=achievementData[i],el=document.querySelector('#routeAchievement');if(!e||!el)return;el.innerHTML=`<small>FLIGHT RECORDER · ${esc(routePoints[i].code)}</small><em class="route-achievement-badge">${esc(e.badge||'MILESTONE')}</em><h4>${esc(e.title)}</h4><p>${esc(e.detail)}</p><span>${esc(e.org)}</span>`;document.querySelectorAll('.achievement-stop').forEach((b,j)=>b.classList.toggle('active',i===j))}
document.querySelectorAll('[data-achievement-index]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.achievementIndex);routeProgress=routePoints[i].p;routeRunning=false;document.querySelector('#routePlay').textContent='RESUME ROUTE';updateRoute();showAchievement(i)}));let prevAchievementIndex=-1;const watchAchievements=()=>{const idx=routePoints.reduce((acc,x,i)=>routeProgress>=x.p?i:acc,0);if(idx!==prevAchievementIndex){prevAchievementIndex=idx;showAchievement(idx)}};const originalRouteUpdate=updateRoute;updateRoute=function(){originalRouteUpdate();watchAchievements()};showAchievement(0);

const aircraftDrawerData={
  boeing:{title:'Boeing 737 NG Family Systems Drawer',systems:['Flight deck displays and flight instrument layout','Electrical power generation and distribution concepts','Navigation, communication and autoflight system context','Maintenance-oriented systems familiarisation across 737-700 / 800 / 900'],training:['EASA Part-66 framework context','Boeing optical / inspection training','Fault isolation and troubleshooting workflow discipline','Avionics and systems-support orientation'],notes:['Operational focus on NG-family systems understanding','Presented as training / systems coverage rather than airline employment evidence','Complements broader avionics and maintenance portfolio context']},
  embraer:{title:'Embraer E-Jet Family Systems Drawer',systems:['ERJ 170 / 190 systems orientation','E-Jet avionics and cockpit systems familiarity','Electrical, navigation and communication subsystem awareness','Maintenance and operational systems context for regional-jet platforms'],training:['Aircraft systems and maintenance training coverage','Avionics and display-system interpretation','Swiss technical training context','Structured systems reasoning and troubleshooting discipline'],notes:['Regional-jet systems perspective complements Boeing training','Used here as portfolio aviation-systems context','Supports the wider aerospace / avionics narrative in the site']}
};
function openAircraftDrawer(id){const d=aircraftDrawerData[id];if(!d)return;const panel=$('#aircraftDrawerPanel');$('#aircraftDrawerTitle').textContent=d.title;$('#aircraftDrawerSystems').innerHTML=d.systems.map(x=>`<span>${esc(x)}</span>`).join('');$('#aircraftDrawerTraining').innerHTML=d.training.map(x=>`<span>${esc(x)}</span>`).join('');$('#aircraftDrawerNotes').innerHTML=d.notes.map(x=>`<span>${esc(x)}</span>`).join('');panel.classList.add('open');panel.scrollIntoView({behavior:'smooth',block:'nearest'});}
document.querySelector('#aviation')?.addEventListener('click',e=>{const b=e.target.closest('[data-aircraft-drawer]');if(b)openAircraftDrawer(b.dataset.aircraftDrawer)});$('#aircraftDrawerClose')?.addEventListener('click',()=>$('#aircraftDrawerPanel')?.classList.remove('open'));

const techNodes2=[...document.querySelectorAll('.tech-node')];let chosenTech='python';const relatedTechnologies={python:['flask','ml','sql','cloud'],flask:['python','sql','cloud'],java:['cpp','sql'],cpp:['java','avionics','ansys'],ml:['python','cv','qiskit'],cv:['ml','avionics','iot'],cyber:['pqc','cloud','python'],qiskit:['pqc','ml'],pqc:['cyber','qiskit'],iot:['avionics','cloud','cv'],ansys:['avionics','cpp'],avionics:['ansys','iot','cv'],sql:['flask','python','cloud'],cloud:['flask','sql','cyber']};
function activateConstellation(id){chosenTech=id;selectTech(id);const connected=relatedTechnologies[id]||[];techNodes2.forEach(n=>{n.classList.toggle('related',connected.includes(n.dataset.techId));n.classList.toggle('dim',n.dataset.techId!==id&&!connected.includes(n.dataset.techId))});const d=techData[id];document.querySelector('#techRelated').textContent='Connected systems: '+connected.map(k=>techData[k]?.title||k).join(' · ');document.querySelector('#techProjects').innerHTML=(d.projects||[]).map(title=>`<button type="button" data-tech-project="${esc(title)}">${esc(title)} ↗</button>`).join('')}
techNodes2.forEach(n=>n.addEventListener('click',()=>activateConstellation(n.dataset.techId)));document.querySelector('#techProjects')?.addEventListener('click',e=>{const b=e.target.closest('[data-tech-project]');if(!b)return;const q=b.dataset.techProject.toLowerCase();const p=PROJECTS.find(x=>x.title.toLowerCase().includes(q)||q.includes(x.title.toLowerCase().split(' ')[0]));if(p)openProject(p.id);else{document.querySelector('#projectSearch').value=b.dataset.techProject;renderProjects();document.querySelector('#projects').scrollIntoView({behavior:'smooth'})}});document.querySelector('#techOpenProject')?.addEventListener('click',()=>{const a=techData[chosenTech]?.projects||[];const p=PROJECTS.find(x=>a.some(s=>x.title.toLowerCase().includes(s.toLowerCase())||s.toLowerCase().includes(x.title.toLowerCase().split(' ')[0])));if(p)openProject(p.id)});document.querySelector('#techSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();techNodes2.forEach(n=>n.classList.toggle('filtered',!!q&&!([n.textContent,n.dataset.group,techData[n.dataset.techId]?.copy,(techData[n.dataset.techId]?.projects||[]).join(' ')].join(' ').toLowerCase().includes(q))));drawTechLines()});document.querySelector('#techReset')?.addEventListener('click',()=>{document.querySelector('#techSearch').value='';techNodes2.forEach(n=>n.classList.remove('filtered','dim','related'));drawTechLines();activateConstellation('python')});activateConstellation('python');
